title: MAGI//ARCHIVE
description: Discovered repositories from the open source frontier
future: true
baseurl: "/repo_posts"
url: "https://tom-doerr.github.io"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
